version: "3.7"

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - default
      - base_share_network

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    depends_on:
      - redis
    ports:
      - "9999:80"
    networks:
      - default
      - base_share_network

  some-rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_VHOST=sensors
    ports:
      - "9998:15672"
    networks:
      - default
      - base_share_network

networks:
  base_share_network:
    external: true